#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width 2
bspc config window_gap 6

bspc config focus_follows_pointer false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color  "#282828"
bspc config focused_border_color "#458588"
bspc config active_border_color  "#d79921"
bspc config presel_feedback_color "#458588"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  1

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Lxappearance state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on
bspc rule -a Connman-gtk state=floating focus=on
bspc rule -a vlc state=tiled focus=on
bspc rule -a Zathura state=tiled focus=on
bspc rule -a MPlayer state=pseudo_tiled focus=on
#bspc rule -a Xfce4-appfinder state=floating focus=on
#bspc rule -a Screenkey manage=off

# compositor manager
# killall picom
pgrep -x picom > /dev/null || picom -m 1 -o 0 &

# Music Player Daemon
#killall mpd
#mpd &

# polybar
$HOME/.config/polybar/launch.sh

